/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.UI.Hospital.MedicalWork.Patient;

import Business.Business;
import Business.Class.Hospital.Medical.Patient;
import Business.UI.Hospital.MedicalWork.Doctor.OutpatientJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author zhangjinming
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel RightPanel;
    private Patient patient;

    private Business bz;
    /**
     * Creates new form PatientWorkAreaJPanel
     */
    public PatientWorkAreaJPanel(JPanel RightPanel,  Business bz,Patient patient) {
        initComponents();
        this.patient = patient;
        this.bz = bz;
        this.RightPanel=RightPanel;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHistory = new javax.swing.JButton();
        btnAppointment = new javax.swing.JButton();
        btnMyProfile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(null);

        btnHistory.setBackground(new java.awt.Color(255, 153, 51));
        btnHistory.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        btnHistory.setText("History");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        add(btnHistory);
        btnHistory.setBounds(515, 214, 142, 217);

        btnAppointment.setBackground(new java.awt.Color(255, 153, 51));
        btnAppointment.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        btnAppointment.setText("Appointment");
        btnAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointmentActionPerformed(evt);
            }
        });
        add(btnAppointment);
        btnAppointment.setBounds(173, 214, 336, 135);

        btnMyProfile.setBackground(new java.awt.Color(255, 153, 51));
        btnMyProfile.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        btnMyProfile.setText("My Profile");
        btnMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyProfileActionPerformed(evt);
            }
        });
        add(btnMyProfile);
        btnMyProfile.setBounds(173, 355, 336, 76);

        jLabel1.setFont(new java.awt.Font("Songti SC", 1, 14)); // NOI18N
        jLabel1.setText("但愿世间无疾苦，宁可架上药生尘。");
        add(jLabel1);
        jLabel1.setBounds(601, 527, 224, 35);

        jLabel2.setFont(new java.awt.Font("Songti SC", 1, 14)); // NOI18N
        jLabel2.setText("Wishing for a realm devoid of ailment and woe, where healing potions idle, cloaked in dust's gentle embrace.");
        add(jLabel2);
        jLabel2.setBounds(203, 568, 622, 20);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel3.setText("Hello,");
        add(jLabel3);
        jLabel3.setBounds(76, 82, 65, 30);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(147, 82, 82, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
    PatientHistoryJPanel php = new PatientHistoryJPanel(RightPanel);
    RightPanel.add("PatientHistoryJPanel", php);
    CardLayout layout = (CardLayout) RightPanel.getLayout();
    layout.next(RightPanel);
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentActionPerformed
        // TODO add your handling code here:
    PatientAppointmentJPanel pap = new PatientAppointmentJPanel(RightPanel, bz, patient);
    RightPanel.add("PatientAppointmentJPanel", pap);
    CardLayout layout = (CardLayout) RightPanel.getLayout();
    layout.next(RightPanel);
    }//GEN-LAST:event_btnAppointmentActionPerformed

    private void btnMyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyProfileActionPerformed
        // TODO add your handling code here:
    PatientProfileJPanel ppp = new PatientProfileJPanel(RightPanel, patient);
    RightPanel.add("PatientProfileJPanel", ppp);
    CardLayout layout = (CardLayout) RightPanel.getLayout();
    layout.next(RightPanel);
    }//GEN-LAST:event_btnMyProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointment;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnMyProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
