/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.UI.Delivery;

import Business.Business;
import Business.Class.BioTech.BioTechCom;
import Business.Class.Delivery.Delivery;
import Business.Class.Delivery.Order;
import Business.Class.Hospital.Hospital;
import Business.Class.Medicine;
import Business.Class.Vaccine;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 15469
 */
public class ProcessingCargoPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessingCargoPanel
     */
    JPanel RightPanel;
    Delivery d;
    Business b;
    public ProcessingCargoPanel(JPanel RightPanel,Delivery d,Business b) {
        initComponents();
        this.RightPanel=  RightPanel;
        this.d=d;
        this.b=b;
        ArrayList <Order> oi = new ArrayList<>();
        String status="";
        status=((String)jComboBox1.getSelectedItem());
        for(Order s : d.getOrders()) {
                if(s.getStatus().equals(status)){
                    oi.add(s);
                    }
        }
        refreshTable1(oi);
    }
    
    public void refreshTable1(ArrayList<Order> oi){
        DefaultTableModel model = (DefaultTableModel)btnCargo.getModel();
        model.setRowCount(0);

        if(oi==null) return;
        for(Order s : oi) {
            Object row[] = new Object[4];
            row[0] = s;
            row[1] = s.getLocation();
            row[2] = s.getAddress();
            row[3] = s.getStatus();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        btnCargo = new javax.swing.JTable();
        btnDelivery = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Processing Cargo");

        btnCargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order id", "From", "To", "Status"
            }
        ));
        jScrollPane2.setViewportView(btnCargo);

        btnDelivery.setText("Delivery");
        btnDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Processing", "Completed", "Cancelled" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnBack))
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(433, 433, 433)
                .addComponent(btnCancel)
                .addGap(12, 12, 12)
                .addComponent(btnDelivery))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)))
                .addGap(7, 7, 7)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelivery)
                    .addComponent(btnCancel)))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        RightPanel.remove(this);
        CardLayout layout = (CardLayout) RightPanel.getLayout();
        layout.previous(RightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryActionPerformed
        // TODO add your handling code here:
        int row = btnCargo.getSelectedRow();
        if(row<0){
           JOptionPane.showMessageDialog(null,"Please select a row from the table first");
            return;
        }
        Order selected = (Order) btnCargo.getValueAt(row, 0);
        for(Hospital h : b.getHospitals()){
            if(h.getName().equals(selected.getAddress())){
                System.out.print("Yes!!!");
                if(selected.getMedicines()!=null){
                    h.DeliveryAddMedicine(selected.getMedicines());
                }
                if(selected.getVaccines()!=null){
                    h.DeliveryAddVaccine(selected.getVaccines());
                }
            }
        
        }
        selected.setStatus("Completed");
        ArrayList <Order> oi = new ArrayList<>();
        String status="";
        status=((String)jComboBox1.getSelectedItem());
        for(Order s : d.getOrders()) {
                if(s.getStatus().equals(status)){
                    oi.add(s);
                    }
        }
        refreshTable1(oi);
    }//GEN-LAST:event_btnDeliveryActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        ArrayList <Order> oi = new ArrayList<>();
        String status="";
        status=((String)jComboBox1.getSelectedItem());
        if(status.equals("Completed")||status.equals("Cancelled")){
            btnCancel.setEnabled(false);
            btnDelivery.setEnabled(false);
        }
        else{
            btnCancel.setEnabled(true);
            btnDelivery.setEnabled(true);
        }
        for(Order s : d.getOrders()) {
                if(s.getStatus().equals(status)){
                    oi.add(s);
                    }
        }
        refreshTable1(oi);
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        int row = btnCargo.getSelectedRow();
        if(row<0){
           JOptionPane.showMessageDialog(null,"Please select a row from the table first");
            return;
        }
        Order selected = (Order) btnCargo.getValueAt(row, 0);
        selected.setStatus("Cancelled");
        for(BioTechCom h : b.getBioTech()){
            if(h.getName().equals(selected.getLocation())){
                System.out.print("Yes!!!");
                if(selected.getMedicines()!=null){
                    System.out.print("Yes!!!");
                    h.DeliveryAddMedicine(selected.getMedicines());
                }
                if(selected.getVaccines()!=null){
                    System.out.print("Yes!!!");
                    h.DeliveryAddVaccine(selected.getVaccines());
                }
            }
        
        }
        ArrayList <Order> oi = new ArrayList<>();
        String status="";
        status=((String)jComboBox1.getSelectedItem());
        for(Order s : d.getOrders()) {
                if(s.getStatus().equals(status)){
                    oi.add(s);
                    }
        }
        refreshTable1(oi);
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JTable btnCargo;
    private javax.swing.JButton btnDelivery;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
