/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.UI;

import Business.Business;
import Business.Class.Hospital.Development.HospitalResearch;
import Business.Class.Hospital.Hospital;
import Business.Class.Hospital.Medical.Doctor;
import Business.Class.Hospital.Medical.Patient;
import Business.Class.Hospital.RearServices.RearServices;
import Business.UI.Hospital.DevelopmentWork.DevelopWorkAreaJPanel;
import Business.UI.Hospital.MedicalWork.Doctor.DoctorWorkAreaJPanel;
import Business.UI.Hospital.MedicalWork.Patient.PatientWorkAreaJPanel;
import Business.UI.Hospital.RearServicesWork.RearServicesWorkAreaJPanel;

import Validation.Validation;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 15469
 */
public class HospitalLoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    JPanel leftPanel;
    Business bz;
    JPanel RightPanel;

    String name;
    String pwd;
    String hospital;
    String type;
    public HospitalLoginPanel(JPanel leftPanel,JPanel RightPanel,Business bz) {
        initComponents();
        this.leftPanel=leftPanel;
        this.bz=bz;
        this.RightPanel= RightPanel;
        type = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpwd = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioPatient = new javax.swing.JRadioButton();
        jRadioDocker = new javax.swing.JRadioButton();
        jRadioAnalysis = new javax.swing.JRadioButton();
        jRadioSupplier = new javax.swing.JRadioButton();
        Back = new javax.swing.JButton();
        hoCombox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        txtpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpwdActionPerformed(evt);
            }
        });

        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login Page");

        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jButton2.setText("Register");

        buttonGroup1.add(jRadioPatient);
        jRadioPatient.setText("Patient");
        jRadioPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioPatientActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioDocker);
        jRadioDocker.setText("Doctor");
        jRadioDocker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDockerActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioAnalysis);
        jRadioAnalysis.setText("Analysis");
        jRadioAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAnalysisActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioSupplier);
        jRadioSupplier.setText("Supplier");
        jRadioSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioSupplierActionPerformed(evt);
            }
        });

        Back.setText("back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        hoCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"", "Boston Rehabilitation Center", "Future Medical Institute", "Verdant Health Hospital" }));

        jLabel4.setText("Hospital");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(26, 26, 26)
                                        .addComponent(txtpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jRadioPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioDocker, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioSupplier)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioAnalysis))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Back)))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(hoCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioPatient)
                    .addComponent(jRadioDocker)
                    .addComponent(jRadioAnalysis)
                    .addComponent(jRadioSupplier))
                .addGap(41, 41, 41)
                .addComponent(jButtonSubmit)
                .addGap(35, 35, 35)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(Back)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpwdActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        leftPanel.remove(this);
        CardLayout layout =  (CardLayout) leftPanel.getLayout();
        layout.next(leftPanel);
    }//GEN-LAST:event_BackActionPerformed

    private void jRadioPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioPatientActionPerformed
        // TODO add your handling code here:
        type="Patient";
    }//GEN-LAST:event_jRadioPatientActionPerformed

    private void jRadioDockerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDockerActionPerformed
        // TODO add your handling code here:
        type="Doctor";
    }//GEN-LAST:event_jRadioDockerActionPerformed

    private void jRadioSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSupplierActionPerformed
        // TODO add your handling code here:
        type="Supplier";
    }//GEN-LAST:event_jRadioSupplierActionPerformed

    private void jRadioAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAnalysisActionPerformed
        // TODO add your handling code here:
        type="Analysis";
    }//GEN-LAST:event_jRadioAnalysisActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // TODO add your handling code here:
        name = txtuser.getText();
        pwd = txtpwd.getText();
        hospital = (String) hoCombox.getSelectedItem();
        Validation v1 = new Validation(bz);
        Object o=v1.IsValidationHospital(hospital, name, pwd, type);
        if(o==null){
            JOptionPane.showMessageDialog(null, "Please input correct account and password!");
            return;
        }
        if(o instanceof Doctor){
            DoctorWorkAreaJPanel dw = new DoctorWorkAreaJPanel(RightPanel, (Doctor) o, bz);
            RightPanel.add("LoginScreen",dw);
            CardLayout layout = (CardLayout) RightPanel.getLayout();
            layout.next(RightPanel);
        }
        else if(o instanceof Patient){
            PatientWorkAreaJPanel pw = new PatientWorkAreaJPanel(RightPanel, bz,(Patient) o);
            RightPanel.add("LoginScreen",pw);
            CardLayout layout = (CardLayout) RightPanel.getLayout();
            layout.next(RightPanel);
        }
        else if(o instanceof RearServices){
            RearServicesWorkAreaJPanel pw = new RearServicesWorkAreaJPanel(RightPanel);
            RightPanel.add("LoginScreen",pw);
            CardLayout layout = (CardLayout) RightPanel.getLayout();
            layout.next(RightPanel);
        }
        else if(o instanceof HospitalResearch){
            DevelopWorkAreaJPanel pw = new DevelopWorkAreaJPanel(RightPanel, bz);
            RightPanel.add("LoginScreen",pw);
            CardLayout layout = (CardLayout) RightPanel.getLayout();
            layout.next(RightPanel);
        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> hoCombox;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioAnalysis;
    private javax.swing.JRadioButton jRadioDocker;
    private javax.swing.JRadioButton jRadioPatient;
    private javax.swing.JRadioButton jRadioSupplier;
    private javax.swing.JTextField txtpwd;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
