/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Business.UI;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author 15469
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    JPanel loginPanel;
    public LoginPanel(JPanel loginPanel) {
        initComponents();
        this.loginPanel=loginPanel;
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TypeComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        TypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hospital", "BioTech", "Medical Analysis", "Medical Supplier","Admin" }));
        TypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login Page");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jButton1)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String type = (String) TypeComboBox.getSelectedItem();

        if(type.equals("Hospital")){
            HospitalLoginPanel ls = new HospitalLoginPanel(loginPanel);
            loginPanel.add("LoginScreen",ls);
            CardLayout layout = (CardLayout) loginPanel.getLayout();
            layout.next(loginPanel);
        }
        if(type.equals("BioTech")){
            BioTechLoginPanel ls = new BioTechLoginPanel(loginPanel);
            loginPanel.add("LoginScreen",ls);
            CardLayout layout = (CardLayout) loginPanel.getLayout();
            layout.next(loginPanel);
        }
        if(type.equals("Medical Analysis")){
            MedicalAnalysisLoginPanel ls = new MedicalAnalysisLoginPanel(loginPanel);
            loginPanel.add("LoginScreen",ls);
            CardLayout layout = (CardLayout) loginPanel.getLayout();
            layout.next(loginPanel);
        }
        if(type.equals("Medical Supplier")){
            MedicalSupplierLoginPanel ls = new MedicalSupplierLoginPanel(loginPanel);
            loginPanel.add("LoginScreen",ls);
            CardLayout layout = (CardLayout) loginPanel.getLayout();
            layout.next(loginPanel);
        }
        if(type.equals("Delivery")){
            DeliveryLoginPanel ls = new DeliveryLoginPanel(loginPanel);
            loginPanel.add("LoginScreen",ls);
            CardLayout layout = (CardLayout) loginPanel.getLayout();
            layout.next(loginPanel);
        }
        if(type.equals("Admin")){
            AdminLoginPanel ls = new AdminLoginPanel(loginPanel);
            loginPanel.add("LoginScreen",ls);
            CardLayout layout = (CardLayout) loginPanel.getLayout();
            layout.next(loginPanel);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> TypeComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
